spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.100:3306/community?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: pzw123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.0.100
    password: pzw123456
    timeout: 1000ms
  cache:
    redis:
      time-to-live: 1h
  servlet:
    multipart:
      # 限制单文件最大大小
      max-file-size: 10MB
      # 限制所有文件最大大小
      max-request-size: 1024MB
  mvc:
    favicon:
      enabled: false
  messages:
    basename: i18n.index

server:
  port: 8080
#  ssl:
#    key-store: buguagaoshu.key
#    key-store-type: PKCS12
#    key-alias: buguagaoshu
#    key-store-password: buguagaoshu

# 应用根目录下的文件名
File:
  ROOT:
    PATH: file
  LOG:
    PATH: log


logging:
  file: log/spring.log
  file.max-history: 7
  file.max-size: 1MB
  level:
    root: info
#    com:
#      buguagaoshu:
#        community:
#          mapper: debug

# 每页广告数
advertisement:
  number: 3

jwt:
  key: buguagaoshu
  ttl: 7200000

# MinIO对象存储
minio:
  server: http://192.168.147.132:9000
  accessKey: admin
  secretKey: admin
  outTime: 86400
  bucket: community


